--------------------------------------------------------
--  DDL DROP STATEMENTS FOR HOTEL ADMINISTRATION   
--------------------------------------------------------
DROP TABLE "WARENART" CASCADE CONSTRAINTS;
DROP TABLE "WARE" CASCADE CONSTRAINTS;
DROP TABLE "ADRESSE" CASCADE CONSTRAINTS;
DROP TABLE "SERVICE" CASCADE CONSTRAINTS;
DROP TABLE "ZIMMER" CASCADE CONSTRAINTS;
DROP TABLE "LAND" CASCADE CONSTRAINTS;
DROP TABLE "REISEPASS" CASCADE CONSTRAINTS;
DROP TABLE "GEHALTSSTUFE" CASCADE CONSTRAINTS;
DROP TABLE "ABTEILUNG" CASCADE CONSTRAINTS;
DROP TABLE "PERSON" CASCADE CONSTRAINTS;
DROP TABLE "BANKINFORMATION" CASCADE CONSTRAINTS;
DROP TABLE "PERSONAL" CASCADE CONSTRAINTS;
DROP TABLE "GAST" CASCADE CONSTRAINTS;
DROP TABLE "LIEFERANTEN" CASCADE CONSTRAINTS;
DROP TABLE "RECHNUNG" CASCADE CONSTRAINTS;
DROP TABLE "BESTELLUNG" CASCADE CONSTRAINTS;
DROP TABLE "ZIMMERBUCHUNG" CASCADE CONSTRAINTS;
DROP TABLE "BESTELLDETAILS" CASCADE CONSTRAINTS;
DROP TABLE "SERVICEDETAILS" CASCADE CONSTRAINTS;
DROP TABLE "ZIMMERBUCHUNGSDETAILS" CASCADE CONSTRAINTS;
DROP TABLE "KUNDENBEWERTUNG" CASCADE CONSTRAINTS;
DROP TABLE "EHEMALIGEMITARBEITER" CASCADE CONSTRAINTS;

DROP SEQUENCE personid_seq;
DROP SEQUENCE adressid_seq;
DROP SEQUENCE lieferantenid_seq;
DROP SEQUENCE warenid_seq;
DROP SEQUENCE warenartid_seq;
DROP SEQUENCE zimmerbuchungsid_seq;
DROP SEQUENCE gehaltsstufeid_seq;
DROP SEQUENCE abteilungsid_seq;
DROP SEQUENCE kontoid_seq;
DROP SEQUENCE bestellungsid_seq;
DROP SEQUENCE bewertungsid_seq;
